Fix bootimg.h:63:9: error: expected identifier or ‘(’ before ‘#pragma’
In this case, there is no struct after the pack instruction which makes gcc fail.